// <auto-generated />
using System;
using LabMovieStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabMovieStore.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250604073437_InitMovieDb")]
    partial class InitMovieDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieStore.Models.Cinema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfHalls")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Musterstraße 1",
                            City = "Berlin",
                            Description = "Modernes Kino mit 8 Sälen, 3D-Technik und Lounge-Bereich.",
                            ImageUrl = "https://www.cinema-paradiso.de/Cinema_Paradiso.jpg",
                            Name = "Cinema Paradiso",
                            NumberOfHalls = 8,
                            PhoneNumber = "030-12345678",
                            TotalSeats = 1200,
                            WebsiteUrl = "https://www.cinema-paradiso.de"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Hauptstraße 99",
                            City = "Hamburg",
                            Description = "Traditionsreiches Programmkino mit besonderem Flair.",
                            ImageUrl = "https://www.filmtheater-stern.de/Filmtheater_Stern.jpg",
                            Name = "Filmtheater Stern",
                            NumberOfHalls = 3,
                            PhoneNumber = "040-98765432",
                            TotalSeats = 350,
                            WebsiteUrl = "https://www.filmtheater-stern.de"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Seepromenade 10",
                            City = "München",
                            Description = "Kino direkt am Wasser mit Open-Air-Veranstaltungen im Sommer.",
                            ImageUrl = "https://www.lichtspielhaus-am-see.de/Lichtspielhaus_am_See.jpg",
                            Name = "Lichtspielhaus am See",
                            NumberOfHalls = 5,
                            PhoneNumber = "089-24681012",
                            TotalSeats = 700,
                            WebsiteUrl = "https://www.lichtspielhaus-am-see.de"
                        });
                });

            modelBuilder.Entity("MovieStore.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<double>("IMDBRating")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Erzählt die Geschichte von Andy Dufresne, einem Banker, der fälschlicherweise wegen Mordes an seiner Frau und deren Liebhaber verurteilt wird und im Gefängnis Freundschaft mit einem Mitgefangenen namens Red schließt, während er über Jahrzehnte hinweg an einem Fluchtplan arbeitet.",
                            Genre = 6,
                            IMDBRating = 8.5,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
                            Price = 13.99m,
                            PublishedDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Die Verurteilten (The Shawshank Redemption)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Erzählt die Geschichte der Corleone-Familie, die von einem Mafia-Patriarchen geführt wird, und die Machtkämpfe und familiären Konflikte, die entstehen, als sein Sohn die Kontrolle übernimmt.",
                            Genre = 6,
                            IMDBRating = 7.5999999999999996,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
                            Price = 19.99m,
                            PublishedDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Der Pate (The Godfather)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Handelt von einem Themenpark mit geklonten Dinosauriern, der von Wissenschaftlern und Besuchern erkundet wird, bis ein Sabotageakt die Sicherheitssysteme außer Kraft setzt und die Dinosaurier freilässt, was zu einer gefährlichen Flucht ums Überleben führt.",
                            Genre = 1,
                            IMDBRating = 9.0,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg",
                            Price = 12.99m,
                            PublishedDate = new DateTime(1993, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
